### PR TITLE
GitHub workflow

### PR DESCRIPTION
**Pull request by MasloMaslane**
After a lot of debugging workflow finally works. Currently tests are only ran on latest ubuntu, but adding other systems that can run in `docker` container should be easy.

### CODE REVIEW

**Comment by MasloMaslane** [comment]
What we could do is on push run tests on only one system (e. g. ubuntu) and when merging we can run tests on all systems. Here is how we could do this: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

**Comment by tonowak** [comment]
Is there a reason why we should limit ourselves to only one system for pushes? I bet we could run all systems without any problems. It shouldn't slow down the GitHub jobs too much because of concurrency and it might find some bugs in the tool sooner.

**Review by tonowak — APPROVED** [review]
Probably we'll want to extend the workflow's functionality, but currently it's a very good start! :rocket:

**Comment by MasloMaslane** [comment]
Oh, I didn't know that GitHub jobs are concurrent. If so, we can run jobs on every push

**Pull request merged**
