### PR TITLE
Add release job

### PR DESCRIPTION
**Pull request by MasloMaslane**
I added release job that runs on GitHub release. I think that it should work.

### CODE REVIEW

**Comment by MasloMaslane** [comment]
I can test it on some other repository

**Comment by tonowak** [comment]
> There is also the option to create a dummy package in the pip's testing repository.

https://packaging.python.org/en/latest/guides/using-testpypi/

**Comment by MasloMaslane** [comment]
OK, I'll test it tomorrow

**Comment by MasloMaslane** [comment]
The workflow works. You can install sinol-make from test pypi: `pip3 install --index-url https://test.pypi.org/legacy --extra-index-url https://pypi.org/simple/ sinol-make`

**Comment by tonowak** [comment]
Great! Then let's change it to the proper pypi repo and merge it :)

**Pull request merged**
