### PR TITLE
Redirect solutions' stderr to `/dev/null`

### LINKED ISSUE #42: Don't print solutions' stderr in `run` command

### PR DESCRIPTION
**Pull request by MasloMaslane**
Closes #42

### CODE REVIEW

**Comment by tonowak** [comment]
Are there other executions (e.g. checkers or inwers) that can print something to stderr and should be ignored, or are solutions the only one?

**Comment by MasloMaslane** [comment]
Checkers are not yet run in sinol-make and stderr from inwers is redirected to stdout

**Comment by tonowak** [comment]
In this PR, yes?

**Comment by MasloMaslane** [comment]
If we want to add this in this PR, we'd have to wait for checkers to be merged into main

**Comment by tonowak** [comment]
Ok, then let's add this change to the checker PR.

**Review by tonowak — APPROVED** [review]

**Comment by tonowak** [comment]
Merge this PR when you'll make a commit in the checker with the change.

**Comment by MasloMaslane** [comment]
Checker output is now redirected to /dev/null ab7bc05a36d0af955646aa762870a5fefbd30f80

**Pull request merged**
